// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaDIP9KYmPiBCPpy1PpREI_BQP9cciitc',
    appId: '1:366003844391:web:fb046acbca616d40dd2502',
    messagingSenderId: '366003844391',
    projectId: 'kihomeproject',
    authDomain: 'kihomeproject.firebaseapp.com',
    storageBucket: 'kihomeproject.firebasestorage.app',
    measurementId: 'G-BWW2DB85SR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrcfP038_Egshosglda2SxMHywkWSrzBw',
    appId: '1:366003844391:android:452fce8f015e0007dd2502',
    messagingSenderId: '366003844391',
    projectId: 'kihomeproject',
    storageBucket: 'kihomeproject.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaDIP9KYmPiBCPpy1PpREI_BQP9cciitc',
    appId: '1:366003844391:web:3ab174149acd20c9dd2502',
    messagingSenderId: '366003844391',
    projectId: 'kihomeproject',
    authDomain: 'kihomeproject.firebaseapp.com',
    storageBucket: 'kihomeproject.firebasestorage.app',
    measurementId: 'G-ZNERGMTQPE',
  );
}
